trigger:
  branches:
    include:
      - main
      - feature/*


pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: TerraformInstall
    displayName: Terraform Install
    jobs:
      - job: TerraformInstall
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'


  - stage: terraforminit
    displayName: terraform init
    jobs: 
      - job: Terraforinit
        displayName: Terraform init
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'Axion-Terraform-Azure 1'
            backendAzureRmStorageAccountName: 'axionterraformstate01'
            backendAzureRmContainerName: 'axion-terraform-lab'
            backendAzureRmKey: 'axion system'

  - stage: 
    displayName: Terraformvalidate
    jobs:
      - job: Terraformvalidate
        displayName: Terraform validate
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'


  - stage: 
    displayName: TerraformPlan
    jobs:
      - job: TerraformPlan
        displayName: Terraform Plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Axion-Terraform-Azure'

