                        # ============================================================
                        # PIPELINE TRIGGER
                        # ============================================================

trigger:
  branches:
    include:
      - main
      - feature/*

                        # ============================================================
                        # AGENT POOL
                        # ============================================================


pool: 
  name: Axion-UI-Build-Pool


stages:

                      # ============================================================
                      # STAGE 1 — BUILD
                      # ============================================================
  - stage: build
    displayName: 'Axion_UI_Build'
    jobs:
      - job: BuildAxionUI   #ID of the job
        displayName: 'Build React Application'



        steps:

                      # --------------------------------------------------------
                      # 1. Checkout source code
                      # --------------------------------------------------------

        - checkout: self
          displayName: 'Checkout GitHub Repository'
        - task: NodeTaskRunnerInstaller@0
          displayName: 'Install Node.js 22'
          inputs:
            versionSpec: '22.x'


                      # --------------------------------------------------------
                      # 2. Check Node.js and npm availability
                      # --------------------------------------------------------


        - script:  |
            echo "chacking Node.js ......."
            if command -v node >/dev/null 2>&1; then
              echo "Node.js is install."
              node --version
            else
              echo "Node.js is not installed."

            fi
            echo "chacking npm....."


            if command -v npm >/dev/null 2>&1; then
              echo "nmp is installed."
              npm --version
            else
              echo "npm is not installed."


            fi
              echo "chacking npm"


                      # --------------------------------------------------------
                      # 3. Check Node.js and npm
                      # --------------------------------------------------------


        - script: |
            echo "Checking Node.js version"
            node --version
            echo "Chacking npm version"
            npm --version
          displayName: 'check Node.js and npm'

                      # --------------------------------------------------------
                      # 4. Install npm Dependencies
                      # --------------------------------------------------------

        - script: |
            echo "installing Project dependencies"
            npm ci
          displayName: 'Install npm dependencies'

